# Generated by Django 5.2.1 on 2025-05-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_excelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='client_po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='client_po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='financial_year',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='sales_document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='excelfile',
            unique_together={('client_po_number', 'client_po_date', 'sales_document')},
        ),
    ]
